name: project

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - .github/workflows/project.yml

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r main/project/requirements.txt

      # Run project tests
      - name: Execute tests
        id: ex_tests
        run: |
          cd main/project
          ./tests.sh || exit 1
